import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const interFontsBlack = localFont({
  src: "./fonts/Inter-Black.woff2",
  variable: "--font-inter-black",
  weight: "100 900",
});
const interFontsBold = localFont({
  src: "./fonts/Inter-Black.woff2",
  variable: "--font-inter-bold",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${interFontsBlack.variable} ${interFontsBold.variable} antialiased`}
      >
  <Theme>{children}</Theme>
      </body>
    </html>
  );
}
